//注释为两个'/'，当前只支持这一种注释方法

void init()
{
	print("init.....");

}
void CalculationTest()
{
	int t1 = GetMsTime();

	int sum = 0;
	int i = 1;
	while (i <= 100)
	{
		int j = 1;
		while (j <= 100)
		{
			sum = sum + i*j;
			j = j + 1;
		}
		i = i + 1;
	}

	int t2 = GetMsTime() - t1;
	print("Calculation result:" + sum);
	print("Calculation time:" + t2 +"ms");
}
void main()
{
	CTest test = new CTest;
	int nVal = test->Add(1,2);
	print(nVal);
	delete test;

	//CalculationTest();

	RunScript(0,"CalculationTest");
}
